language: objective-c
osx_image: xcode11
xcode_workspace: Youtube.xcworkspace
xcode_scheme: Youtube
cache:
  - bundler
  - cocoapods
before_install:
  - bundle install
  - bundle exec pod install --repo-update
install:
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
script:
  - ./scripts/linter